# Generated by Django 6.0.5 on 2026-05-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_attribute_options_remove_attribute_category_and_more'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(default=dict, help_text='Ex: {"Couleur": "Rouge", "Taille": "XL"}'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.CharField(blank=True, help_text='Pour les attributs texte/nombre', max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='categories.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='categories.attributevalue')),
            ],
            options={
                'verbose_name': 'Caractéristique produit',
                'db_table': 'product_attributes',
                'unique_together': {('product', 'attribute', 'value')},
            },
        ),
    ]
