# Generated by Django 6.0.5 on 2026-05-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_end_product_discount_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube/Vimeo/autre')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/video_thumbnails/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'verbose_name': 'Vidéo produit',
                'db_table': 'product_videos',
                'ordering': ['-is_primary', 'order'],
            },
        ),
    ]
