# Generated by Django 6.0.5 on 2026-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_installment',
            field=models.BooleanField(default=True, verbose_name='Paiement échelonné autorisé'),
        ),
    ]
