# Generated by Django 6.0.5 on 2026-05-21 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_attribute_options_remove_attribute_category_and_more'),
        ('orders', '0002_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Taux décimal, ex: 0.10 = 10%', max_digits=5)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=0, help_text='Frais fixe par commande (en plus du taux)', max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande pour appliquer cette règle', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='categories.category')),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rule', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Règle de commission',
                'db_table': 'commission_rules',
            },
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_order_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payout', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=15)),
                ('method', models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('wallet', 'Portefeuille interne')], default='bank_transfer', max_length=15)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Reversement vendeur',
                'db_table': 'vendor_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate_applied', models.DecimalField(decimal_places=4, max_digits=5)),
                ('flat_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_amount', models.DecimalField(decimal_places=2, help_text='Montant dû au vendeur = order_amount - commission_amount', max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='vendors.store')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commissionrule')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.vendorpayout')),
            ],
            options={
                'verbose_name': 'Commission',
                'db_table': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
