# Generated by Django 6.0.5 on 2026-05-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Attribut'},
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='categories.category'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_filterable',
            field=models.BooleanField(default=True, help_text='Afficher dans les filtres'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('select', 'Liste de choix'), ('multiselect', 'Choix multiples'), ('text', 'Texte libre'), ('number', 'Nombre'), ('boolean', 'Oui/Non'), ('color', 'Couleur')], default='select', max_length=20),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.CharField(blank=True, help_text='Ex: cm, kg, L', max_length=30),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Ex: #FF0000 pour les attributs couleur', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom d'icône (ex: shopping-bag)", max_length=100),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
