# Generated by Django 6.0.5 on 2026-05-21 04:24

import apps.affiliate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clic affilié',
                'db_table': 'affiliate_clicks',
            },
        ),
        migrations.CreateModel(
            name='AffiliateConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('paid', 'Payé')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Conversion affilié',
                'db_table': 'affiliate_conversions',
            },
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_url', models.URLField(blank=True)),
                ('code', models.CharField(default=apps.affiliate.models.generate_affiliate_code, max_length=20, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lien affilié',
                'db_table': 'affiliate_links',
            },
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traité'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Paiement affilié',
                'db_table': 'affiliate_payouts',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.affiliate.models.generate_affiliate_code, max_length=8, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profil affilié',
                'db_table': 'affiliate_profiles',
            },
        ),
    ]
