# Generated by Django 6.0.5 on 2026-05-21 04:24

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments_count', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Complété'), ('defaulted', 'En défaut')], default='active', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='orders.order')),
            ],
            options={
                'verbose_name': 'Plan de paiement fractionné',
                'db_table': 'installment_plans',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('overdue', 'En retard')], default='pending', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.installmentplan')),
            ],
            options={
                'verbose_name': 'Versement',
                'db_table': 'installments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('wave', 'Wave'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('wallet', 'Portefeuille')], max_length=20)),
                ('gateway', models.CharField(choices=[('cinetpay', 'CinetPay'), ('paydunya', 'PayDunya'), ('flutterwave', 'Flutterwave'), ('internal', 'Interne')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('reference', models.CharField(default=core.utils.generate_reference, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('processed', 'Traité')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'db_table': 'refunds',
            },
        ),
    ]
