# Generated by Django 6.0.5 on 2026-05-24 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_add_delivery_profile'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='installment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='installment_proofs/'),
        ),
        migrations.AddField(
            model_name='installment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='installment',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='installment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_installments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='contract_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='extended_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='extension_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='relay_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='deliveries.relaypoint'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('uploaded', 'Preuve envoyée'), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('paid', 'Payé'), ('overdue', 'En retard')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente signature'), ('active', 'Actif'), ('extended', 'Prolongé'), ('completed', 'Complété'), ('defaulted', 'En défaut'), ('forfeited', 'Article saisi')], default='pending', max_length=20),
        ),
    ]
