# Generated by Django 6.0.5 on 2026-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_extend_installment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
