# Generated by Django 6.0.5 on 2026-05-21 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_discount_end_product_discount_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='CI', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('payment_terms', models.CharField(blank=True, help_text='Ex: 30 jours net, paiement à la commande…', max_length=100)),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Délai de livraison moyen en jours')),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande', max_digits=14)),
                ('quality_rating', models.CharField(choices=[('A', 'Excellent'), ('B', 'Bon'), ('C', 'Acceptable'), ('D', 'Médiocre'), ('F', 'Défaillant')], default='B', max_length=1)),
                ('quality_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Score qualité 0-100 mis à jour automatiquement', max_digits=5)),
                ('defect_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='% de livraisons avec défauts', max_digits=5)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='% de livraisons à temps', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False, help_text="Fournisseur homologué par l'admin")),
                ('notes', models.TextField(blank=True)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Résilié')], default='draft', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='suppliers/contracts/')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission / remise négociée (%)', max_digits=5)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Contrat fournisseur',
                'db_table': 'supplier_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('orders_completed', models.PositiveIntegerField(default=0)),
                ('orders_late', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('defective_items', models.PositiveIntegerField(default=0)),
                ('total_items_received', models.PositiveIntegerField(default=0)),
                ('quality_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Rapport performance fournisseur',
                'db_table': 'supplier_performance_reports',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('supplier', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, help_text='Référence du produit chez le fournisseur', max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=5)),
                ('min_order_quantity', models.PositiveIntegerField(default=1)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Override du délai fournisseur pour ce produit', null=True)),
                ('is_preferred', models.BooleanField(default=False, help_text='Fournisseur préféré pour ce produit')),
                ('last_price_update', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='suppliers.supplier')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Produit fournisseur',
                'db_table': 'supplier_products',
                'unique_together': {('supplier', 'product', 'variant')},
            },
        ),
    ]
