# Generated by Django 6.0.5 on 2026-05-21 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
