# Generated by Django 6.0.5 on 2026-05-21 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_product_discount_end_product_discount_start_and_more'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='live/thumbnails/')),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('live', 'En direct'), ('ended', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=15)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('stream_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stream_url', models.URLField(blank=True, help_text='URL HLS/RTMP fournie par le service de streaming')),
                ('room_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('peak_viewer_count', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_live_sessions', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Session live',
                'db_table': 'live_sessions',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécial live (remplace le prix normal si renseigné)', max_digits=12, null=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_featured', models.BooleanField(default=False, help_text='Produit actuellement mis en avant')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_appearances', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_appearances', to='products.productvariant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_products', to='live.livesession')),
            ],
            options={
                'verbose_name': 'Produit live',
                'db_table': 'live_products',
                'ordering': ['position'],
                'unique_together': {('session', 'product', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='LiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_order', to='orders.order')),
                ('live_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='live.liveproduct')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_orders', to='live.livesession')),
            ],
            options={
                'verbose_name': 'Commande live',
                'db_table': 'live_orders',
            },
        ),
        migrations.CreateModel(
            name='LiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('comment_type', models.CharField(choices=[('comment', 'Commentaire'), ('like', 'Like'), ('love', 'Love'), ('fire', 'Feu'), ('clap', 'Applaudissement')], default='comment', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_comments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='live.livesession')),
            ],
            options={
                'verbose_name': 'Commentaire live',
                'db_table': 'live_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Pour les anonymes', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='live.livesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spectateur live',
                'db_table': 'live_viewers',
            },
        ),
    ]
