# Generated by Django 6.0.5 on 2026-05-21 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('sending', "En cours d'envoi"), ('sent', 'Envoyée'), ('cancelled', 'Annulée')], default='draft', max_length=15)),
                ('audience', models.CharField(choices=[('all', 'Tous les utilisateurs'), ('customers', 'Clients (ont commandé)'), ('vendors', 'Vendeurs'), ('inactive', 'Inactifs (>30 jours sans commande)'), ('new', 'Nouveaux inscrits (<7 jours)'), ('segment', 'Segment personnalisé')], default='all', max_length=15)),
                ('subject', models.CharField(blank=True, help_text='Objet email', max_length=500)),
                ('content', models.TextField(help_text='Corps du message / HTML email')),
                ('cta_url', models.URLField(blank=True, help_text='Lien bouton appel à action')),
                ('cta_label', models.CharField(blank=True, default='Voir les offres', max_length=100)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Laisser vide pour envoi immédiat', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'db_table': 'marketing_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedCartReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('converted', 'Converti'), ('expired', 'Expiré')], default='pending', max_length=10)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relance panier abandonné',
                'db_table': 'marketing_abandoned_cart_reminders',
                'ordering': ['-created_at'],
                'unique_together': {('cart', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('opened', 'Ouvert'), ('clicked', 'Cliqué'), ('failed', 'Échec'), ('unsubscribed', 'Désabonné')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinataire campagne',
                'db_table': 'marketing_campaign_recipients',
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp'), ('all', 'Tous')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Désabonnement',
                'db_table': 'marketing_unsubscribes',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
