# Generated by Django 6.0.5 on 2026-05-21 04:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('home_delivery', 'Livraison à domicile'), ('relay_point', 'Point relais')], default='home_delivery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assigné'), ('picked_up', 'Récupéré'), ('in_transit', 'En transit'), ('delivered', 'Livré'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='deliveries/signatures/')),
                ('qr_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livraison',
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique livraison',
                'db_table': 'delivery_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cities', models.JSONField(default=list)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_days', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'db_table': 'delivery_zones',
            },
        ),
        migrations.CreateModel(
            name='RelayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Point relais',
                'db_table': 'relay_points',
            },
        ),
    ]
