# Generated by Django 6.0.5 on 2026-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relaypoint',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='relaypoint',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
