# Generated by Django 6.0.5 on 2026-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_add_relay_manager_price_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaypoint',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
