# Generated by Django 6.0.5 on 2026-05-24 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_relay_phone_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('velo', 'Vélo'), ('pied', 'À pied'), ('other', 'Autre')], default='moto', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('coverage_zones', models.ManyToManyField(blank=True, related_name='delivery_persons', to='deliveries.deliveryzone')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil livreur',
                'db_table': 'delivery_profiles',
            },
        ),
    ]
