# Generated by Django 6.0.5 on 2026-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_add_delivery_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
