# Generated by Django 6.0.5 on 2026-05-21 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_product_discount_end_product_discount_start_and_more'),
        ('sav', '0001_initial'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image retour produit',
                'db_table': 'product_return_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QualityDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('cosmetic', 'Cosmétique'), ('functional', 'Fonctionnel'), ('safety', 'Sécurité'), ('packaging', 'Emballage'), ('labeling', 'Étiquetage'), ('missing_parts', 'Pièces manquantes'), ('wrong_specs', 'Spécifications incorrectes'), ('damage', 'Dommage physique'), ('contamination', 'Contamination'), ('other', 'Autre')], max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Mineur'), ('major', 'Majeur'), ('critical', 'Critique')], max_length=10)),
                ('description', models.TextField()),
                ('quantity_affected', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Défaut qualité',
                'db_table': 'quality_defects',
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('inspection_type', models.CharField(choices=[('reception', 'Réception fournisseur'), ('customer_return', 'Retour client'), ('periodic', 'Contrôle périodique'), ('complaint', 'Suite plainte / contentieux'), ('pre_shipment', 'Avant expédition')], max_length=20)),
                ('quantity_inspected', models.PositiveIntegerField(default=1)),
                ('quantity_passed', models.PositiveIntegerField(default=0)),
                ('quantity_failed', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('pending', 'En attente'), ('passed', 'Conforme'), ('failed', 'Non conforme'), ('partial', 'Partiellement conforme')], default='pending', max_length=15)),
                ('grade', models.CharField(blank=True, choices=[('A', 'Excellent (≥95%)'), ('B', 'Bon (80-94%)'), ('C', 'Acceptable (60-79%)'), ('D', 'Médiocre (40-59%)'), ('F', 'Défectueux (<40%)')], max_length=1, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inspection qualité',
                'verbose_name_plural': 'Inspections qualité',
                'db_table': 'quality_inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality/inspections/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Image inspection qualité',
                'db_table': 'quality_inspection_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQualityNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('acknowledged', 'Accusé réception'), ('resolved', 'Résolu'), ('disputed', 'Contesté'), ('closed', 'Clôturé')], default='draft', max_length=15)),
                ('quantity_defective', models.PositiveIntegerField(default=0)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_response', models.TextField(blank=True)),
                ('supplier_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Avis de non-conformité fournisseur',
                'db_table': 'supplier_quality_notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductQualityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent (≥95%)'), ('B', 'Bon (80-94%)'), ('C', 'Acceptable (60-79%)'), ('D', 'Médiocre (40-59%)'), ('F', 'Défectueux (<40%)')], default='B', max_length=1)),
                ('quality_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Score 0-100 calculé automatiquement', max_digits=5)),
                ('defect_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='% unités défectueuses sur toutes les inspections', max_digits=5)),
                ('return_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='% de retours sur les ventes totales', max_digits=5)),
                ('total_units_inspected', models.PositiveIntegerField(default=0)),
                ('total_units_defective', models.PositiveIntegerField(default=0)),
                ('total_returns', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_profile', to='products.product')),
            ],
            options={
                'verbose_name': 'Fiche qualité produit',
                'db_table': 'product_quality_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('source', models.CharField(choices=[('customer', 'Client'), ('vendor', 'Vendeur'), ('supplier', 'Fournisseur')], default='customer', max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('defective', 'Produit défectueux'), ('wrong_item', 'Mauvais article reçu'), ('not_as_described', 'Non conforme à la description'), ('damaged_delivery', 'Endommagé à la livraison'), ('missing_parts', 'Pièces manquantes'), ('quality_issue', 'Problème de qualité'), ('size_issue', 'Problème de taille/format'), ('changed_mind', "Changement d'avis"), ('supplier_defect', 'Défaut fournisseur confirmé'), ('expired', 'Produit périmé'), ('other', 'Autre')], max_length=25)),
                ('description', models.TextField(help_text='Description détaillée du problème par le client / vendeur')),
                ('condition', models.CharField(choices=[('sealed', 'Neuf / Non ouvert'), ('good', 'Bon état'), ('acceptable', 'État acceptable'), ('damaged', 'Endommagé'), ('defective', 'Défectueux'), ('unusable', 'Inutilisable')], default='defective', help_text='État constaté du produit retourné', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'En attente de réception'), ('received', 'Produit reçu'), ('under_inspection', "En cours d'inspection"), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('replacement_pending', 'Remplacement en cours'), ('replacement_sent', 'Remplacement expédié'), ('refunded', 'Remboursé'), ('restocked', 'Remis en stock'), ('disposed', 'Mis au rebut'), ('completed', 'Clôturé')], default='pending', max_length=25)),
                ('resolution', models.CharField(blank=True, choices=[('refund_wallet', 'Remboursement portefeuille'), ('refund_original', 'Remboursement moyen original'), ('replacement', 'Remplacement produit'), ('store_credit', 'Avoir boutique'), ('repair', 'Réparation'), ('partial_refund', 'Remboursement partiel'), ('no_action', 'Aucune action')], max_length=20, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('stock_updated', models.BooleanField(default=False)),
                ('restock', models.BooleanField(default=False, help_text='True = remis en stock, False = mis au rebut')),
                ('replacement_tracking', models.CharField(blank=True, max_length=100)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('return_tracking_number', models.CharField(blank=True, max_length=100)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='support.dispute')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='orders.orderitem')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to='products.product')),
                ('replacement_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_returns', to='products.product')),
                ('replacement_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_returns', to='products.productvariant')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to=settings.AUTH_USER_MODEL)),
                ('sav_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='sav.savrequest')),
            ],
            options={
                'verbose_name': 'Retour produit',
                'verbose_name_plural': 'Retours produits',
                'db_table': 'product_returns',
                'ordering': ['-created_at'],
            },
        ),
    ]
