# Generated by Django 6.0.5 on 2026-05-21 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_supplierorder_supplier_and_more'),
        ('orders', '0002_initial'),
        ('products', '0003_product_discount_end_product_discount_start_and_more'),
        ('quality', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreturn',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='supplier_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='inventory.supplierorderitem'),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_returns', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productreturnimage',
            name='product_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quality.productreturn'),
        ),
        migrations.AddField(
            model_name='productreturnimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='support.dispute'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='products.product'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='product_return',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection', to='quality.productreturn'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='supplier_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='inventory.supplierorderitem'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='qualitydefect',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.qualityinspection'),
        ),
        migrations.AddField(
            model_name='qualityinspectionimage',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quality.qualityinspection'),
        ),
        migrations.AddField(
            model_name='supplierqualitynotice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quality_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierqualitynotice',
            name='dispute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_notices', to='support.dispute'),
        ),
        migrations.AddField(
            model_name='supplierqualitynotice',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_notices', to='quality.qualityinspection'),
        ),
        migrations.AddField(
            model_name='supplierqualitynotice',
            name='product_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_notices', to='quality.productreturn'),
        ),
        migrations.AddField(
            model_name='supplierqualitynotice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_notices', to='suppliers.supplier'),
        ),
    ]
