# Generated by Django 6.0.5 on 2026-05-21 04:24

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('is_certified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('is_verified', models.BooleanField(default=False)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='StoreDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('business_reg', 'Registre de commerce'), ('tax_cert', 'Attestation fiscale')], max_length=20)),
                ('file', models.FileField(upload_to='stores/documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Document boutique',
                'db_table': 'store_documents',
            },
        ),
    ]
