# Generated by Django 6.0.5 on 2026-05-21 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_product_discount_end_product_discount_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Note interne visible uniquement par le staff')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message SAV',
                'db_table': 'sav_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sav/attachments/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sav.savmessage')),
            ],
            options={
                'verbose_name': 'Pièce jointe SAV',
                'db_table': 'sav_message_attachments',
            },
        ),
        migrations.CreateModel(
            name='SavRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('return', 'Retour'), ('exchange', 'Échange'), ('repair', 'Réparation')], max_length=20)),
                ('reason', models.CharField(choices=[('defective', 'Produit défectueux'), ('wrong_item', 'Mauvais article reçu'), ('not_as_described', 'Non conforme à la description'), ('damaged', 'Endommagé à la livraison'), ('size_issue', 'Problème de taille/format'), ('changed_mind', "Changement d'avis"), ('missing_parts', 'Pièces manquantes'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('processing', 'En traitement'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('wallet', 'Portefeuille'), ('original_payment', 'Moyen de paiement original'), ('bank_transfer', 'Virement bancaire')], max_length=20)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('return_tracking_number', models.CharField(blank=True, max_length=100)),
                ('return_received_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='products.product')),
                ('exchange_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='products.productvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sav_requests', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sav_requests', to='orders.orderitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sav_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sav_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande SAV',
                'verbose_name_plural': 'Demandes SAV',
                'db_table': 'sav_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='savmessage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sav.savrequest'),
        ),
        migrations.CreateModel(
            name='SavRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sav/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sav.savrequest')),
            ],
            options={
                'verbose_name': 'Image SAV',
                'db_table': 'sav_request_images',
                'ordering': ['order'],
            },
        ),
    ]
