# Generated by Django 6.0.5 on 2026-05-21 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('monthly', 'Rapport mensuel complet'), ('sales', 'Analyse ventes'), ('customers', 'Comportement client'), ('vendors', 'Performance vendeurs'), ('products', 'Performance produits'), ('quality', 'Qualité & Retours'), ('delivery', 'Livraison'), ('comparison', 'Comparaison M vs M-1')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('compare_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compare_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, help_text='Toutes les métriques sérialisées')),
                ('summary', models.TextField(blank=True, help_text='Résumé narratif auto-généré')),
                ('key_insights', models.JSONField(default=list, help_text='Liste des insights clés')),
                ('is_auto', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='audit/reports/')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Rapport audit',
                'verbose_name_plural': 'Rapports audit',
                'db_table': 'audit_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('sales', 'Ventes'), ('customers', 'Clients'), ('products', 'Produits'), ('vendors', 'Vendeurs'), ('quality', 'Qualité'), ('delivery', 'Livraison'), ('finance', 'Finance'), ('support', 'Support')], max_length=15)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], max_length=10)),
                ('metric_name', models.CharField(max_length=100)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('previous_value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('variation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('threshold', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_kpi_alerts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_alerts', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Alerte KPI',
                'verbose_name_plural': 'Alertes KPI',
                'db_table': 'audit_kpi_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('orders_total', models.PositiveIntegerField(default=0)),
                ('orders_completed', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('orders_refunded', models.PositiveIntegerField(default=0)),
                ('orders_pending', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commandes complétées / total commandes (%)', max_digits=6)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('returning_customers', models.PositiveIntegerField(default=0)),
                ('total_active_customers', models.PositiveIntegerField(default=0)),
                ('cart_abandonment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_purchase_frequency', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('unique_products_sold', models.PositiveIntegerField(default=0)),
                ('stockout_products', models.PositiveIntegerField(default=0)),
                ('returns_count', models.PositiveIntegerField(default=0)),
                ('return_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('disputes_opened', models.PositiveIntegerField(default=0)),
                ('disputes_resolved', models.PositiveIntegerField(default=0)),
                ('failed_inspections', models.PositiveIntegerField(default=0)),
                ('avg_delivery_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_product_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('support_tickets', models.PositiveIntegerField(default=0)),
                ('avg_ticket_resolution_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='vendors.store')),
            ],
            options={
                'verbose_name': 'Snapshot mensuel',
                'db_table': 'audit_monthly_snapshots',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month', 'store')},
            },
        ),
    ]
