# Generated by Django 6.0.5 on 2026-05-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('sales', 'Ventes'), ('vendors', 'Vendeurs'), ('products', 'Produits'), ('payments', 'Paiements'), ('users', 'Utilisateurs')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('ready', 'Prêt'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rapport',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
