# Generated by Django 6.0.5 on 2026-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('card_type', models.CharField(choices=[('info', 'Info'), ('promo', 'Promo')], default='info', max_length=10)),
                ('bg_color', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carte latérale',
                'db_table': 'sidebar_cards',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='slider',
            name='accent_color',
            field=models.CharField(blank=True, default='#1C3525', max_length=20),
        ),
        migrations.AddField(
            model_name='slider',
            name='badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='slider',
            name='bg_gradient',
            field=models.CharField(blank=True, default='from-[#F7941D] via-[#f9a84d] to-[#fbbf24]', max_length=200),
        ),
        migrations.AddField(
            model_name='slider',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='slider',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
