# Generated by Django 6.0.5 on 2026-05-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='images',
        ),
        migrations.AddField(
            model_name='productreview',
            name='vendor_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='vendor_reply',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.productreview')),
            ],
            options={
                'db_table': 'review_images',
                'ordering': ['order'],
            },
        ),
    ]
