# Generated by Django 6.0.5 on 2026-05-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('order', 'Commande'), ('payment', 'Paiement'), ('delivery', 'Livraison'), ('review', 'Avis'), ('system', 'Système'), ('promo', 'Promotion'), ('chat', 'Message')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], default='in_app', max_length=20)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order', models.BooleanField(default=True)),
                ('email_promo', models.BooleanField(default=True)),
                ('sms_order', models.BooleanField(default=True)),
                ('sms_promo', models.BooleanField(default=False)),
                ('push_order', models.BooleanField(default=True)),
                ('push_promo', models.BooleanField(default=True)),
                ('whatsapp_order', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Préférences notifications',
                'db_table': 'notification_preferences',
            },
        ),
    ]
