# Generated by Django 6.0.5 on 2026-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Commande'), ('payment', 'Paiement'), ('delivery', 'Livraison'), ('review', 'Avis'), ('system', 'Système'), ('promo', 'Promotion'), ('chat', 'Message'), ('sav', 'SAV'), ('dispute', 'Litige'), ('return', 'Retour'), ('ticket', 'Ticket Support')], max_length=20),
        ),
    ]
