# Generated by Django 6.0.5 on 2026-05-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Durée du message vocal en secondes', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_waveform',
            field=models.JSONField(blank=True, help_text="Forme d'onde encodée pour la visualisation (liste de floats 0-1)", null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='transcript',
            field=models.TextField(blank=True, help_text='Transcription automatique du message vocal'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('audio', 'Message vocal'), ('file', 'Fichier'), ('voice', 'Message vocal')], default='text', max_length=10),
        ),
    ]
